# Generated by Django 2.2.3 on 2019-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sessionStudent',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
