# Generated by Django 2.2.3 on 2019-07-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190706_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sessionStudent',
        ),
    ]
