# Generated by Django 2.2.3 on 2019-07-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_sessionstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sessionStudent',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
