# Generated by Django 2.2.3 on 2019-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_sessionstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sessionStudent',
            field=models.IntegerField(),
        ),
    ]
