# Generated by Django 2.2.3 on 2019-07-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190706_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sessionStudent',
        ),
    ]
