# Generated by Django 2.2.3 on 2019-07-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20190707_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredcourse',
            name='offered_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='others.Course'),
        ),
    ]
