# Generated by Django 2.2.3 on 2019-07-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_auto_20190706_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='members',
            new_name='students',
        ),
    ]
