# Generated by Django 2.2.3 on 2019-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_auto_20190707_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='referrence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
